version: "3.3"

services:
  app:
    container_name: dhruvmirror3-mltb
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "8002:80"
